name: "issue_comment"
on:
  issue_comment:
    types: [created]
  

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: run-something
      if: github.event.issue_comment.body == 'akshay'
      run: echo start the CLA testing flow

